# Generated by Django 6.0.6 on 2026-09-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpost',
            name='donation_location',
            field=models.CharField(blank=True, help_text='Where this donation will be prepared/collected from', max_length=255),
        ),
        migrations.AddField(
            model_name='mealrequest',
            name='request_location',
            field=models.CharField(blank=True, help_text='Pickup/request location for this meal request', max_length=255),
        ),
    ]
